[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32 @ 6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library @ 1.12.6
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display @ 3.0.15
extra_scripts = pre:tools/pio_build_ui.py
