"""Generate identical pixel fonts and palettes for host preview and firmware."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
data = json.loads((root / 'web/display.json').read_text())
(root / 'web/display-data.mjs').write_text('// Generated by tools/build_display.py\nexport const DISPLAY_DATA = ' + json.dumps(data, separators=(',', ':')) + ';\n')
rows = []
for key, pattern in data['font'].items():
    code = ord(key)
    rows.append('  {%d, %d, {%s}},' % (code, len(pattern[0]), ','.join(str(int(row, 2)) for row in pattern)))
colours = ['  {' + ','.join('0x' + c[1:] for c in palette) + '},' for palette in data['palettes'].values()]
(root / 'include/DisplayData.h').write_text('''// Generated by tools/build_display.py
#pragma once
#include <cstdint>
namespace Display {
struct Glyph { unsigned code; int width; uint8_t rows[5]; };
static const Glyph font[] = {
''' + '\n'.join(rows) + '\n};\nstatic const uint32_t palettes[][3] = {\n' + '\n'.join(colours) + '\n};\n}\n')
