#!/usr/bin/env python3
"""Download legacy PokéAPI cries and prepare mono IMA ADPCM for the ESP32.

Downloads and ffmpeg conversion are explicit (--download / --convert). Normal
PlatformIO builds only concatenate the checked-in converted assets, offline.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/cries'
REVISION = 'ef687b18f0ce17169b4b4c09175819f7ade92f0f'
SOURCE = f'https://raw.githubusercontent.com/PokeAPI/cries/{REVISION}/cries/pokemon/legacy'
RATE = 8000
BLOCK = 256


def download(number):
    target = ASSETS / 'legacy' / f'{number}.ogg'
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists():
        temporary = target.with_suffix('.part')
        subprocess.run(['curl', '--fail', '--silent', '--show-error', '--location',
                        '--retry', '3', '--max-time', '60', f'{SOURCE}/{number}.ogg',
                        '--output', str(temporary)], check=True)
        if not temporary.read_bytes().startswith(b'OggS'):
            raise ValueError(f'Invalid Ogg cry #{number}')
        temporary.replace(target)


def chunks(wav):
    if wav[:4] != b'RIFF' or wav[8:12] != b'WAVE':
        raise ValueError('Invalid WAV')
    result = {}
    offset = 12
    while offset + 8 <= len(wav):
        tag, size = struct.unpack_from('<4sI', wav, offset)
        result[tag] = wav[offset + 8:offset + 8 + size]
        offset += 8 + size + size % 2
    return result


def convert(number):
    source = ASSETS / 'legacy' / f'{number}.ogg'
    with tempfile.TemporaryDirectory(prefix='matrix-cry-') as directory:
        target = Path(directory) / 'cry.wav'
        subprocess.run(['ffmpeg', '-v', 'error', '-i', str(source), '-ac', '1',
                        '-ar', str(RATE), '-c:a', 'adpcm_ima_wav', '-block_size',
                        str(BLOCK), str(target)], check=True)
        wav = chunks(target.read_bytes())
        fmt = wav[b'fmt ']
        codec, channels, rate, _, alignment, bits = struct.unpack_from('<HHIIHH', fmt)
        if (codec, channels, rate, alignment, bits) != (17, 1, RATE, BLOCK, 4):
            raise ValueError(f'Unexpected ADPCM format #{number}')
        samples = struct.unpack_from('<I', wav[b'fact'])[0]
        content = wav[b'data']
        if not content or len(content) % BLOCK:
            raise ValueError(f'Invalid ADPCM blocks #{number}')
        converted = ASSETS / 'adpcm' / f'{number}.ima'
        converted.parent.mkdir(parents=True, exist_ok=True)
        converted.write_bytes(content)
        return {'id': number, 'samples': samples, 'bytes': len(content),
                'oggSha256': hashlib.sha256(source.read_bytes()).hexdigest(),
                'sha256': hashlib.sha256(content).hexdigest()}


def pack():
    catalogue = json.loads((ASSETS / 'catalogue.json').read_text())
    data = bytearray()
    table = []
    for entry in catalogue['entries']:
        content = (ASSETS / 'adpcm' / f'{entry["id"]}.ima').read_bytes()
        if hashlib.sha256(content).hexdigest() != entry['sha256']:
            raise ValueError(f'Cry #{entry["id"]} checksum mismatch')
        table.append(f'  {{{len(data)}u, {len(content)}u, {entry["samples"]}u}},')
        data.extend(content)
    (ASSETS / 'cries.bin').write_bytes(data)
    (ROOT / 'include/cry_assets.h').write_text(
        '// Generated by tools/prepare_cries.py. Legacy cries from PokéAPI.\n'
        '#pragma once\n#include <stdint.h>\n'
        'struct CryAsset { uint32_t offset, size, samples; };\n'
        f'constexpr uint32_t CRY_SAMPLE_RATE = {RATE};\n'
        f'constexpr uint32_t CRY_BLOCK_SIZE = {BLOCK};\n'
        'static const CryAsset CRY_ASSETS[] = {\n' + '\n'.join(table) + '\n};\n')
    duration = sum(entry['samples'] for entry in catalogue['entries']) / RATE
    print(f'Packed {len(table)} cries: {len(data)} bytes, {duration:.1f} seconds total.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--download', action='store_true')
    parser.add_argument('--convert', action='store_true')
    args = parser.parse_args()
    numbers = range(1, 252)
    if args.download:
        with ThreadPoolExecutor(max_workers=8) as pool:
            list(pool.map(download, numbers))
        print('Downloaded 251 legacy cries.', flush=True)
    if args.convert:
        with ThreadPoolExecutor(max_workers=4) as pool:
            entries = list(pool.map(convert, numbers))
        (ASSETS / 'catalogue.json').write_text(json.dumps(
            {'source': 'https://github.com/PokeAPI/cries', 'revision': REVISION,
             'style': 'legacy', 'rate': RATE, 'blockSize': BLOCK, 'entries': entries},
            separators=(',', ':')) + '\n')
    pack()
