#!/usr/bin/env python3
"""Import downloaded Blue Moon Falls archives and pack GIFs for LittleFS.

Original GIFs remain in assets/crystal. Each is gzip-compressed independently in
one pack, avoiding LittleFS block overhead for hundreds of tiny files.
"""
import argparse
import gzip
import hashlib
import json
import re
from pathlib import Path
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parents[1]
SOURCE = 'https://bluemoonfalls.com/pages/general/crystal-gif-archive'


def import_archives(normal, shiny, names):
    with ZipFile(names) as archive:
        labels = {hashlib.sha256(archive.read(name)).hexdigest(): Path(name).stem
                  for name in archive.namelist() if name.endswith('.gif')}
    entries = []
    for variant, path in [('normal', normal), ('shiny', shiny)]:
        with ZipFile(path) as archive:
            for filename in archive.namelist():
                match = re.fullmatch(r'(\d+)(-[a-z])?\.gif', filename)
                if not match:
                    continue
                stem = Path(filename).stem
                content = archive.read(filename)
                if not content.startswith((b'GIF87a', b'GIF89a')):
                    raise ValueError('Invalid GIF: ' + filename)
                if variant == 'normal':
                    label = labels[hashlib.sha256(content).hexdigest()]
                else:
                    label = next(e['name'] for e in entries if e['key'] == 'normal/' + stem)
                target = ROOT / 'assets/crystal' / variant / filename
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(content)
                entries.append({'key': variant + '/' + stem, 'id': int(match[1]),
                                'name': label, 'variant': variant,
                                'url': '/sprites/crystal/' + variant + '/' + filename})
    if len(entries) != 552:
        raise ValueError(f'Expected 552 archive sprites, found {len(entries)}')
    (ROOT / 'assets/crystal/catalogue.json').write_text(json.dumps(
        {'source': SOURCE, 'entries': entries}, separators=(',', ':')) + '\n')


def pack_assets():
    catalogue = json.loads((ROOT / 'assets/crystal/catalogue.json').read_text())
    entries = sorted(catalogue['entries'], key=lambda e: (e['variant'], e['id'], e['key']))
    pack = bytearray()
    table = []
    for entry in entries:
        compressed = gzip.compress((ROOT / 'assets/crystal' / (entry['key'] + '.gif')).read_bytes(), mtime=0)
        table.append(f'  {{"{entry["url"]}", {len(pack)}u, {len(compressed)}u}},')
        pack.extend(compressed)
    data = ROOT / 'data'
    data.mkdir(exist_ok=True)
    (data / 'crystal.bin').write_bytes(pack)
    (data / 'crystal.json').write_text(json.dumps(
        {**catalogue, 'entries': entries}, separators=(',', ':')))
    (data / 'crystal.json.gz').write_bytes(gzip.compress((data / 'crystal.json').read_bytes(), mtime=0))
    (ROOT / 'include/crystal_assets.h').write_text(
        '// Generated by tools/prepare_crystal.py; original GIFs in assets/crystal.\n'
        '#pragma once\n#include <Arduino.h>\n'
        'struct CrystalAsset { const char* path; uint32_t offset; uint32_t size; };\n'
        'static const CrystalAsset CRYSTAL_ASSETS[] = {\n' + '\n'.join(table) + '\n};\n')
    print(f'Packed {len(entries)} GIFs: {len(pack)} bytes; catalogue {(data / "crystal.json").stat().st_size} bytes.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--normal', type=Path)
    parser.add_argument('--shiny', type=Path)
    parser.add_argument('--names', type=Path)
    args = parser.parse_args()
    if args.normal or args.shiny or args.names:
        if not all([args.normal, args.shiny, args.names]):
            parser.error('Supply all three archive paths, or none to repack existing assets.')
        import_archives(args.normal, args.shiny, args.names)
    pack_assets()
